// Pure builders/mergers for the setup wizard. No I/O. Deterministic.
import { parseDotEnv } from '../config/env.js';

/** answers → config/credentials.json object */
export function buildCredentialsJson(answers) {
    if (answers.mode === 'remote') {
        return {
            blacklight: { ...answers.blacklight },
            scraperCredentials: { ...answers.scraperCredentials },
        };
    }
    const out = {};
    for (const [platform, section] of Object.entries(answers.platforms ?? {})) {
        if (section) out[platform] = section;
    }
    return out;
}

/** answers → .env file text (trailing newline; deterministic order; unset flags omitted) */
export function buildDotEnv(answers) {
    const lines = ['# Generated by `npm run setup` — do not commit (git-ignored).'];
    lines.push(`NODE_ENV=${answers.mode === 'remote' ? 'production' : 'development'}`);
    if (answers.headless === true) lines.push('LINKEDIN_HEADLESS=true');
    if (answers.strictEmpty === true) lines.push('SCRAPER_STRICT_EMPTY=true');
    lines.push(`SCRAPER_MODE=${answers.scraperMode || 'interactive'}`);
    if (answers.port && Number(answers.port) !== 3001) lines.push(`PORT=${answers.port}`);
    return lines.join('\n') + '\n';
}

/**
 * Shallow top-level merge: next's keys replace existing's matching key; others preserved.
 * Returns a shallow copy — nested objects are shared with `next`. The wizard must supply
 * COMPLETE platform sections (a partial section fully replaces the existing one).
 */
export function mergeCredentials(existing, next) {
    return { ...(existing ?? {}), ...(next ?? {}) };
}

/** keep existing lines/comments; override keys present in nextText; append new ones */
export function mergeDotEnv(existingText, nextText) {
    const nextKv = parseDotEnv(nextText);
    const seen = new Set();
    const out = [];
    // split() on a trailing-newline file yields a final "" element; drop ONE
    // so appended keys don't get a spurious blank line before them. (Line
    // endings are normalized to LF — the scraper targets Linux/macOS hosts.)
    const rawLines = String(existingText ?? '').split(/\r?\n/);
    if (rawLines.length && rawLines[rawLines.length - 1] === '') rawLines.pop();
    for (const rawLine of rawLines) {
        const line = rawLine;
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) { out.push(line); continue; }
        const eq = trimmed.indexOf('=');
        const key = eq > 0 ? trimmed.slice(0, eq).trim() : null;
        if (key && key in nextKv) {
            if (seen.has(key)) continue; // drop later duplicates of an overridden key
            out.push(`${key}=${nextKv[key]}`);
            seen.add(key);
        } else {
            out.push(line);
        }
    }
    for (const [k, v] of Object.entries(nextKv)) {
        if (!seen.has(k)) out.push(`${k}=${v}`);
    }
    return out.join('\n').replace(/\n+$/, '') + '\n';
}
