// Environment configuration — loaded once at startup, validated, immutable.
// No secrets are logged here; values flow through to modules that need them.

import fs from 'fs';
import os from 'os';
import path from 'path';

const DEFAULTS = Object.freeze({
    PORT: 3001,
    LOG_LEVEL: 'info',
    QUEUE_CHECK_INTERVAL_MS: 30_000,
    QUEUE_CHECK_STARTUP_DELAY_MS: 5_000,
    CDP_PORT: 9222,
    CHROME_PATH: process.platform === 'win32'
        ? 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'
        : '/usr/bin/google-chrome',
    METRICS_PUSH_INTERVAL_MS: 30_000,
    LOKI_PUSH_INTERVAL_MS: 5_000,
    LOKI_PUSH_BATCH_MAX: 200,
    // The backend no longer drives location-specific scraping (only role-based).
    // Per-platform scrapers still need a location string for their search URLs,
    // so each instance falls back to this. Override with SCRAPER_DEFAULT_LOCATION
    // if you want to scope a scraper to a tighter region.
    SCRAPER_DEFAULT_LOCATION: 'United States',
});

function toInt(value, fallback) {
    const n = Number.parseInt(value, 10);
    return Number.isFinite(n) ? n : fallback;
}

// ── .env support (zero-dependency) ──────────────────────────────────────
// No `dotenv` package. parseDotEnv is pure (unit-tested). applyDotEnv
// only sets keys that are currently undefined, so a real environment /
// launchd / NSSM value ALWAYS wins over the file. loadDotEnvFile is the
// thin fs wrapper; absent file → inert (no behavior change for anyone
// without a .env). Generated by `npm run setup`.
export function parseDotEnv(text) {
    const out = {};
    if (typeof text !== 'string') return out;
    for (const rawLine of text.split(/\r?\n/)) {
        const line = rawLine.trim();
        if (!line || line.startsWith('#')) continue;
        const eq = line.indexOf('=');
        if (eq < 1) continue; // no key, or `=value`
        const key = line.slice(0, eq).trim();
        if (!key) continue;
        let value = line.slice(eq + 1).trim();
        if (value.length >= 2
            && ((value[0] === '"' && value[value.length - 1] === '"')
             || (value[0] === "'" && value[value.length - 1] === "'"))) {
            value = value.slice(1, -1);
        }
        out[key] = value;
    }
    return out;
}

export function applyDotEnv(kv, env = process.env) {
    for (const [k, v] of Object.entries(kv)) {
        if (env[k] === undefined) env[k] = v;
    }
}

function loadDotEnvFile(envPath = path.join(process.cwd(), '.env')) {
    try {
        if (!fs.existsSync(envPath)) return;
        applyDotEnv(parseDotEnv(fs.readFileSync(envPath, 'utf-8')), process.env);
    } catch { /* best-effort: a broken .env must never crash startup */ }
}

function loadCredentialsFile() {
    const credentialsPath = path.join(process.cwd(), 'config', 'credentials.json');
    try {
        return JSON.parse(fs.readFileSync(credentialsPath, 'utf-8'));
    } catch {
        return null;
    }
}

function buildConfig() {
    loadDotEnvFile();
    const credentials = loadCredentialsFile();

    const blacklight = credentials?.blacklight ?? null;
    // The credentials API is the same backend + same scraper key as blacklight
    // ({apiUrl, apiKey} shape). When no dedicated scraperCredentials section is
    // present, fall back to the blacklight config so the REMOTE pool is used.
    const scraperCredentials = credentials?.scraperCredentials ?? credentials?.blacklight ?? null;

    return Object.freeze({
        port: toInt(process.env.PORT, DEFAULTS.PORT),
        logLevel: process.env.LOG_LEVEL || DEFAULTS.LOG_LEVEL,

        queue: Object.freeze({
            checkIntervalMs: toInt(process.env.QUEUE_CHECK_INTERVAL_MS, DEFAULTS.QUEUE_CHECK_INTERVAL_MS),
            startupDelayMs: toInt(process.env.QUEUE_CHECK_STARTUP_DELAY_MS, DEFAULTS.QUEUE_CHECK_STARTUP_DELAY_MS),
            defaultLocation: process.env.SCRAPER_DEFAULT_LOCATION || DEFAULTS.SCRAPER_DEFAULT_LOCATION,
        }),

        linkedin: Object.freeze({
            chromePath: process.env.CHROME_PATH || DEFAULTS.CHROME_PATH,
            cdpPort: toInt(process.env.CDP_PORT, DEFAULTS.CDP_PORT),
        }),

        blacklight: blacklight
            ? Object.freeze({ apiUrl: blacklight.apiUrl, apiKey: blacklight.apiKey })
            : null,

        scraperCredentialsApi: scraperCredentials
            ? Object.freeze({ apiUrl: scraperCredentials.apiUrl, apiKey: scraperCredentials.apiKey })
            : null,

        // Raw credentials file — only the platform sections (linkedin/glassdoor/indeed/techfetch).
        // Consumed by the credential-api client's no-config LOCAL fallback (when
        // neither blacklight nor scraperCredentials API config is present).
        rawCredentials: credentials ? Object.freeze(credentials) : null,

        // Observability — telemetry is proxied through the Blacklight API
        // (api.qpeakhire.com) using the existing scraper API key. The
        // backend injects identity labels server-side and forwards to
        // Pushgateway + Loki over the private network. If `blacklight` is
        // not configured, telemetry is disabled but the scraper still
        // runs and exposes /metrics locally for debugging.
        //
        // Override env vars (all optional):
        //   TELEMETRY_URL    — base URL (defaults to blacklight.apiUrl)
        //   TELEMETRY_KEY    — API key (defaults to blacklight.apiKey)
        //   INSTANCE_ID      — per-host instance label (defaults to os.hostname())
        //   SCRAPER_MODE     — 'daemon' enables offline alerts
        telemetry: Object.freeze({
            baseUrl: process.env.TELEMETRY_URL || blacklight?.apiUrl || null,
            apiKey: process.env.TELEMETRY_KEY || blacklight?.apiKey || null,
            metricsPushIntervalMs: toInt(process.env.METRICS_PUSH_INTERVAL_MS, DEFAULTS.METRICS_PUSH_INTERVAL_MS),
            logsPushIntervalMs: toInt(process.env.LOKI_PUSH_INTERVAL_MS, DEFAULTS.LOKI_PUSH_INTERVAL_MS),
            logsBatchMax: toInt(process.env.LOKI_PUSH_BATCH_MAX, DEFAULTS.LOKI_PUSH_BATCH_MAX),
            instance: process.env.INSTANCE_ID || os.hostname(),
            mode: process.env.SCRAPER_MODE === 'daemon' ? 'daemon' : 'interactive',
        }),
    });
}

// Singleton — loaded once, never mutated.
let cached = null;

export function getConfig() {
    if (!cached) {
        cached = buildConfig();
    }
    return cached;
}

// Invalidate the singleton and rebuild from disk. Used at startup after the
// first-run preflight (src/setup/ensure-api-key.js) writes a fresh
// config/credentials.json — another module may already have triggered
// getConfig() at import time (src/http/client.js reads it at module scope),
// so a plain getConfig() would return the stale pre-write config.
export function reloadConfig() {
    cached = null;
    return getConfig();
}

// Test-only helper; not used in production code paths.
export function resetConfigForTest() {
    cached = null;
}
